# config/routes.yaml

app_numero_sorteo:
    path: /sorteo/numero/{maximo}
    controller: App\Controller\SorteoController::numero
    defaults:
        maximo: 100

app_suma:
    path: /suma/{num1}/{num2}
    controller: App\Controller\SorteoController::suma
    defaults:
        num1: 2
        num2: 2

app_index:
    path: /
    controller: App\Controller\SorteoController::index

app_euromillones:
    path: /sorteo/euromillones
    controller: App\Controller\SorteoController::euromillones